version: '3.1'

networks:
  default:
    external:
      name: colombia

volumes:
 colombia-mysql-data:
   external: true

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
    - 3306:3306
    volumes:
      - "./colombia-mysql/mysql:/etc/mysql/mysql.conf.d"
      - "colombia-mysql-data:/var/lib/mysql"
      - "./colombia-mysql/scripts:/tmp/scripts"
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
