version: '3'

networks:
  default:
    external:
      name: apptransmosquera

volumes:
 apptransmosquera-mysql-data:
   external: true

services:
  mysql:
    image: mysql:latest
    container_name: dbusers
    ports:
    - 3306:3306
    volumes:
      - "./apptransmosquera-mysql/mysql:/etc/mysql/mysql.conf.d"
      - "apptransmosquera-mysql-data:/var/lib/mysql"
      - "./apptransmosquera-mysql/scripts:/tmp/scripts"
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DB}
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: dbusers
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 300M
    restart: always
    ports:
      - 8081:80
